# Generated by Django 6.0.4 on 2026-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(choices=[('XS', 'Очень маленький'), ('S', 'Маленький'), ('M', 'Средний'), ('L', 'Большой'), ('XL', 'Очень большой'), ('XXL', 'Очень очень большой'), ('XXXL', 'Очень очень очень большой')])),
            ],
        ),
    ]
