# Generated by Django 6.0.4 on 2026-07-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_suitcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcard',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
